#!/bin/bash

render() {
    active_w=$(xprop -root _NET_CURRENT_DESKTOP | awk '{print $NF}')

    win_ids=$(xprop -root _NET_CLIENT_LIST | sed 's/.*# //' | tr ',' ' ')

    declare -A used_map
    for win in $win_ids; do
        ws=$(xprop -id "$win" _NET_WM_DESKTOP 2>/dev/null | awk '{print $NF}')
        [[ -n "$ws" ]] && used_map[$ws]=1
    done

    output="(box :space-evenly false :class \"workspaces\" :spacing 7 :valign \"center\""

    for workspace in {0..8}; do
        class="workspace-btn"
        [[ ${used_map[$workspace]} ]] && class="$class used"
        [[ "$active_w" == "$workspace" ]] && class="$class active"

        output="$output (eventbox :width 10 :height 10 :valign \"center\" \
:class \"$class\" :onclick \"wmctrl -s $workspace\")"
    done

    output="$output)"

    echo "$output"
}

xprop -spy -root _NET_CURRENT_DESKTOP _NET_CLIENT_LIST | while read; do
    render
done
