set -g mouse on
set -g set-clipboard on

set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
##########
set  -g base-index 1
set  -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on
##########
unbind C-b
set -g prefix C-s
bind-key C-s send-prefix
##########
bind v new-window 'vi'
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -n M-Tab next-window
bind r source-file ~/.config/tmux/tmux.conf
##########
set-window-option -g mode-keys vi
bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel
unbind -T copy-mode-vi MouseDragEnd1Pane

##########
set  -g status-right-style          'fg=white'
set  -g status-style                'fg=white'
setw -g window-status-style         'fg=white'
setw -g window-status-current-style 'fg=white'

# Kanagawa (Wave) - Dark variant
thm_bg="#1F1F28"
thm_fg="#DCD7BA"
thm_cyan="#7FB4CA"
thm_black="#16161D"
thm_lbg="#2A2A37"
thm_llbg="#363646"
thm_magenta="#957FB8" 
thm_pink="#E46876"
thm_red="#E46876"
thm_green="#98BB6C"
thm_yellow="#E6C384"  
thm_blue="#7E9CD8"
thm_orange="#FFA066"
thm_blue4="#223249"

set -g window-status-current-format "#[fg=${thm_fg},bg=${thm_lbg}] #{window_name} "
set -g window-status-format "#[fg=#{thm_fg},bg=${thm_black}] #{window_name} "
set -g window-status-separator ""
set -g status-style "bg=${thm_black}"

set -g status-position top
set -g status-justify left
set -g status-left "#[fg=${thm_blue}] [#S] "
set -g status-right "#[fg=${thm_blue}]#(echo '#{pane_current_path}' | rev | cut -d'/' -f-2 | rev) "
set -g status-left-length 30
